### ISSUE TITLE
Keeping a reference to a future silence exceptions

### ISSUE THREAD

**Issue by sametmax** [python/asyncio#397]
Take this simple code:

```python
import asyncio

loop = asyncio.get_event_loop()

async def foo():
    print('foo')
    raise ValueError('Hu ?')

asyncio.ensure_future(foo())

print('Starting loop')
loop.run_forever()
```

It will output:

```
Starting loop
foo
Task exception was never retrieved
future: <Task finished coro=<foo() done, defined at foo.py:5> exception=ValueError('Hu ?',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "foo.py", line 7, in foo
    raise ValueError('Hu ?')
ValueError: Hu ?
```

But if you do something that seems innocent like:

```
# ...
future = asyncio.ensure_future(foo())
# ...
```
Suddenly you'll get:

```
Starting loop
foo
```

And nothing more. No traceback, no message even with PYTHONASYNCIODEBUG=1 and logging set to DEBUG.

Actually you would not even know you have an error unless you are looking for it. 

If you really want to keep a reference to the future, the solution is to use a weakref, which means I suppose, that asyncio probably do something in `__del__` that display the error:

```python
import asyncio
import weakref

loop = asyncio.get_event_loop()

async def foo():
    print('foo')
    raise ValueError('Hu ?')

future = weakref.ref(asyncio.ensure_future(foo()))

print('Starting loop')
loop.run_forever()
```

However, this is almost impossible to know. We spent a day on this one, without even first knowing we had an error, and then tracking down every single line trying to understand what we did wrong: signal handlers, exception handlers, task factories, debug modes, try/except/finally... Until we removed the variable almost by accident, in a "there-is-no-way-that's-it" last resort gesture.

I'm going to add weakref everywhere I need to keep a ref to a task, but I think it should not be something a end user should need to know. You really want debugging to work out of the box, not under some very specific conditions that seems to depend of the internals of the implementation.

**Comment by alexbrun** [comment]
Same problem, different day!

**Comment by 1st1** [comment]
Maybe we can make a workaround? Let's say in debug mode we could have a weakset of all Futures. Would that solve the problem?

**Comment by asvetlov** [comment]
@1st1 looks like a good solution

**Comment by 1st1** [comment]
@sametmax Wait... When I tried to run the below script I got a warning from asyncio (on Ctrl-C) that an exception wasn't retrieved.

```python
import asyncio
import weakref

loop = asyncio.get_event_loop()

async def foo():
    print('foo')
    raise ValueError('Hu ?')

future = asyncio.ensure_future(foo())

print('Starting loop')
loop.run_forever()
```

Is your problem that there was no warning while the program was executing?

**Comment by graingert** [comment]
```pytb
graingert@kvell  ~  cat foo.py 
import asyncio
import weakref

loop = asyncio.get_event_loop()

async def foo():
    print('foo')
    raise ValueError('Hu ?')

async def bar():
    pass

future = asyncio.ensure_future(foo())

print('Starting loop')
loop.run_until_complete(bar())
 graingert@kvell  ~  python3 foo.py
Starting loop
foo
Task exception was never retrieved
future: <Task finished coro=<foo() done, defined at foo.py:6> exception=ValueError('Hu ?',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "foo.py", line 8, in foo
    raise ValueError('Hu ?')
ValueError: Hu ?
```

**Comment by Martiusweb** [comment]
The thing is that as long as one keeps a reference to the future, we can't know if the exception will eventually be retrieved or not, that's why the task exception isn't shown until this reference is cleared (when the program exists, for instance).

When the debug mode is enabled, maybe we can trigger the warning after a given timeout. For instance,
in Future.set_exception(), we can add a callback set to trigger after (say) 2 seconds, and cancel that callback if exception() or result() is called.

Instead of a timeout, we can wait until the loop is idle, which somehow indicates that the user is not planning to retrieve the exception soon.

What do you think of this idea?

**Comment by asvetlov** [comment]
User shouldn't get exception immediately.
It's perfectly fine to push the failed future into a queue and retrieve it sometimes.
The delay between exception causing and it's retrieving may be much more than 2 sec, e.g. for case of web crawler iterating over huge site.

**Comment by Martiusweb** [comment]
The issue raised here is that during development, the user can't have a quick feedback about the fact that an exception happened in a Task, that's why I suggest to have a short timeout (with PYTHONASYNCIODEBUG=1) after which the exception is displayed, possibly with a message explaining why it's a good practice to await the task.

In production, I'm okay with the current behavior.

**Comment by gvanrossum** [comment]
> a short timeout (with PYTHONASYNCIODEBUG=1) after which the exception is
displayed

That's an interesting idea; how could it be implemented?

**Comment by 1st1** [comment]
> .. that's why I suggest to have a short timeout (with PYTHONASYNCIODEBUG=1) after which the exception is displayed, possibly with a message explaining why it's a good practice to await the task.

I understand the idea, but I think it might be very confusing for people to see some messages for futures that are supposed to stay unresolved for some time. That said, you should probably make a patch and try it with your code. We can then try it too and see if it really works.

**Comment by graingert** [comment]
The alternative is the bluebird approach where if an exception is not
synchronously handled a method on the loop is called with the Exception
instance. set_maybe_uncaught_exception_handler

**Comment by Martiusweb** [comment]
I wrote a first draft of my idea, which can be seen here:
https://github.com/Martiusweb/asyncio/commit/0986fc6611d6e4e9a8261e12632b3405c005a2fc

This is obviously incomplete : I only tested it with python 3.5 (I need to build python 3.3 to test the code added to _TracebackLogger), and complete unit tests are missing. But the main idea is here:
The message is displayed after 2 seconds when a reference is kept, and I made sure that this mechanism doesn't hold a reference to the future. (I tried several implementations, but the weakref is probably the easiest/safest).

**Comment by achimnol** [comment]
Replacing `asyncio.ensure_future` with a wrapper like below always shows exceptions when they occur. Maybe this should become a default behavior in the debugging mode, and/or documentation should mention the pitfall and describe a mitigation like this.

```python
def ensure_future(coro):
    loop = asyncio.get_event_loop()
    fut = asyncio.ensure_future(coro)
    def exception_logging_done_cb(fut):
        try:
            e = fut.exception()
        except asyncio.CancelledError:
            return
        if e is not None:
            loop.call_exception_handler({
                'message': 'Unhandled exception in async future',
                'future': fut,
                'exception': e,
            })
    fut.add_done_callback(exception_logging_done_cb)
    return fut
```

**Comment by askabelin** [comment]
The problem still exists. Spend a whole day trying to understand what's wrong. When we have configured logging then there is no way to notice an exception. Debug and @achimnol 's function do not help.

This code shows the exception when I hit  Ctrl-C:

```python
import asyncio

async def bug():
    return 1 / 0

loop = asyncio.get_event_loop()
future = asyncio.ensure_future(bug())
loop.run_forever()
```

But this one is completely silent:

```python
import asyncio
import logging.config

logging.config.dictConfig({
    'version': 1,
    'handlers': {
        'default': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['default'],
            'level': 'DEBUG',
        },
    }
})

async def bug():
    return 1 / 0

loop = asyncio.get_event_loop()
future = asyncio.ensure_future(bug())
loop.run_forever()
```
I'm using Python 3.6.1.

**Comment by AVee** [comment]
I just noticed the same behavior when using asyncio.run_coroutine_threadsafe():

    import asyncio

    async def bug():
        print('HI!')
        raise Exception("AAA")
    
    loop = asyncio.get_event_loop()
    f = asyncio.run_coroutine_threadsafe(bug(), loop)
    loop.run_forever()
    loop.close()

This even happens when the reference to the returned future is not kept. So it looks like a run_coroutine_threadsafe() also prevents garbage collection of the task...

**Comment by gvanrossum** [comment]
> I just noticed the same behavior ...

Can you be specific about the exception or behavior you're getting? And is that the full source code? (It can't be, there are at least some imports missing.)

**Comment by AVee** [comment]
The import got lost in markdown, that's fixed now.

Doing some further testing I also found I've been slightly put on the wrong foot by running in Idle (on Windows). 
This is what I've got right now:

    import asyncio

    async def bug():
        print('HI!')
        raise Exception("AAA")

    loop = asyncio.get_event_loop()

    # Case 1: Prints the exception
    asyncio.ensure_future(bug())

    # Case 2: Original issue, exception is silenced.
    #f = asyncio.ensure_future(bug())

    # Case 3: Same behaviour as case 2, exception is silenced.
    #asyncio.run_coroutine_threadsafe(bug(), loop)

    # Run for 5 seconds because Ctrl+C doesn't work on Windows...
    loop.run_until_complete(asyncio.sleep(5))

Case 1 always immediately prints the exception like this:

    HI!
    Task exception was never retrieved
    future: <Task finished coro=<bug() done, defined at C:\Users\ARJAN\Desktop\aioexcept.py:3> exception=Exception('AAA',)>
    Traceback (most recent call last):
      File "C:\Users\ARJAN\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 240, in _step
        result = coro.send(None)
      File "C:\Users\ARJAN\Desktop\aioexcept.py", line 5, in bug
        raise Exception("AAA")
    Exception: AAA

When running this from a shell the exception gets printed on shutdown (which makes sense, because that's when the future goes out of scope). I've checked this against 3.5.4 and 3.6.3 on Windows and 3.5.3 on Linux.
What put me on the wrong foot here was that when running in IDLE because it keeps the shell running.

For case 3 I'd expect the exception to be printed instantly just like in case 1, or at least at shutdown. Neither happens, the output is just `HI!` and nothing else. There is no indication of the failure anywhere.

On a higher level, I get how async execution will cause issues like this, but it makes debugging really hard when exceptions occur where you didn't expect them. What would really help is a place where all these exceptions end up, at least in some debugging mode. (If something like that exists I haven't found it yet...) Personally I'd like a setting where any failed task gets send to the warnings module.

**Comment by gvanrossum** [comment]
Looking at the asyncio source code for `run_coroutine_threadsafe()`, it looks like creates a `concurrent.futures.Future` wrapping an `asyncio.Future` object created from your coroutine. I don't want to look into how `concurrent.futures` works (though its source in the stdlib is also pure Python) but I suspect that at some point a reference to the outer Future is kept (probably in the worker machinery).

For your wish (which is not unreasonable) you should really use bugs.python.org, this tracker is dead (asyncio is no longer maintained as a separate project).
